import{getState,update,undoAction,redoAction,uid}from'./store.js';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),snap=n=>Math.round(n/10)*10;
let selected=null,drag=null,view={x:0,y:0,scale:1},pointers=new Map(),pinch=null;
const shapes=['round','square','rectangle','booth','bar','l-booth','banquet','polygon'];
function seatDots(t){const n=clamp(Number(t.capacity)||1,1,30),dots=[];for(let i=0;i<n;i++){const a=Math.PI*2*i/n-Math.PI/2;dots.push(`<i class="seat-dot" style="left:calc(50% + ${Math.cos(a)*52}% - 6px);top:calc(50% + ${Math.sin(a)*52}% - 6px)"></i>`)}return dots.join('')}
function tableHtml(t){return `<button class="fp-table ${t.shape} ${selected===t.id?'selected':''}" data-table="${t.id}" style="left:${t.x}px;top:${t.y}px;width:${t.width}px;height:${t.height}px;transform:rotate(${t.rotation||0}deg)">${seatDots(t)}<span><b>${t.number}</b><small>${t.capacity} seats</small></span></button>`}
function objectHtml(o){return `<div class="fp-object ${o.type}" data-object="${o.id}" style="left:${o.x}px;top:${o.y}px;width:${o.width}px;height:${o.height}px;transform:rotate(${o.rotation||0}deg)"><span>${o.label||o.type}</span></div>`}
export function mountFloorPlan(root,{editor=false}={}){root.innerHTML=`<section class="floor-module ${editor?'editing':''}"><header class="module-head"><div><h2>${editor?'Floor Plan Editor':'Floor Plan'}</h2><p>${editor?'Drag, resize, rotate, zoom and arrange the restaurant.':'Live seating map'}</p></div>${editor?`<div class="toolbar"><button data-cmd="undo">Undo</button><button data-cmd="redo">Redo</button><button data-cmd="zoom-out">−</button><button data-cmd="zoom-in">+</button><button data-cmd="fit">Fit</button><button class="primary" data-cmd="done">Done</button></div>`:''}</header>${editor?palette():''}<div class="floor-viewport"><div class="floor-canvas"></div></div><aside class="floating-inspector collapsed"></aside></section>`;render(root,editor);bind(root,editor)}
function palette(){const furniture=['wall','door','window','host-stand','kitchen','restroom','waiting','patio','bar-area','private-room'];return `<div class="palette">${shapes.map(s=>`<button data-add-table="${s}">${s}</button>`).join('')}${furniture.map(s=>`<button data-add-object="${s}">${s.replace('-',' ')}</button>`).join('')}</div>`}
function render(root,editor){const s=getState(),canvas=root.querySelector('.floor-canvas');canvas.style.transform=`translate(${view.x}px,${view.y}px) scale(${view.scale})`;canvas.innerHTML=(s.objects||[]).map(objectHtml).join('')+(s.tables||[]).map(tableHtml).join('');inspector(root,editor)}
function inspector(root,editor){const box=root.querySelector('.floating-inspector'),t=getState().tables.find(x=>x.id===selected);if(!editor||!t){box.classList.add('collapsed');box.innerHTML='';return}box.classList.remove('collapsed');box.innerHTML=`<div class="grab"></div><div class="inspector-row"><strong>Table ${t.number}</strong><button data-close-inspector>×</button></div><div class="quick-grid"><button data-seat="-1">− Seat</button><span>${t.capacity}</span><button data-seat="1">+ Seat</button><button data-rotate="-90">↺ 90°</button><button data-rotate="90">↻ 90°</button><select data-shape>${shapes.map(x=>`<option ${x===t.shape?'selected':''}>${x}</option>`).join('')}</select></div><details><summary>Advanced</summary><label>Table number<input data-number value="${t.number}"></label><label>Section<input data-section value="${t.section}"></label><label>Width<input data-width type="number" value="${t.width}"></label><label>Height<input data-height type="number" value="${t.height}"></label><div class="actions"><button data-duplicate>Duplicate</button><button class="danger" data-delete>Delete</button></div></details>`;bindInspector(root)}
function bind(root,editor){root.onclick=e=>{const cmd=e.target.dataset.cmd;if(cmd==='undo')undoAction().then(()=>render(root,editor));if(cmd==='redo')redoAction().then(()=>render(root,editor));if(cmd==='zoom-in'){view.scale=clamp(view.scale+.15,.35,2.5);render(root,editor)}if(cmd==='zoom-out'){view.scale=clamp(view.scale-.15,.35,2.5);render(root,editor)}if(cmd==='fit'){view={x:0,y:0,scale:Math.min(1,(root.clientWidth-30)/1000)};render(root,editor)}if(cmd==='done')root.dispatchEvent(new CustomEvent('frontseat:editor-close',{bubbles:true}));if(e.target.dataset.addTable)addTable(e.target.dataset.addTable,root);if(e.target.dataset.addObject)addObject(e.target.dataset.addObject,root)};const vp=root.querySelector('.floor-viewport');vp.addEventListener('pointerdown',e=>pointerDown(e,root,editor));window.addEventListener('pointermove',e=>pointerMove(e,root,editor),{passive:false});window.addEventListener('pointerup',e=>pointerUp(e,root,editor));window.addEventListener('pointercancel',e=>pointerUp(e,root,editor));vp.addEventListener('wheel',e=>{if(!editor)return;e.preventDefault();view.scale=clamp(view.scale+(e.deltaY<0?.1:-.1),.35,2.5);render(root,editor)},{passive:false})}
function pointerDown(e,root,editor){if(!editor)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const el=e.target.closest('[data-table],[data-object]');if(el?.dataset.table){selected=el.dataset.table;const t=getState().tables.find(x=>x.id===selected);drag={kind:'table',id:selected,startX:e.clientX,startY:e.clientY,x:t.x,y:t.y};render(root,editor);return}if(pointers.size===2){const p=[...pointers.values()];pinch={distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),scale:view.scale,x:view.x,y:view.y,midX:(p[0].x+p[1].x)/2,midY:(p[0].y+p[1].y)/2};return}drag={kind:'pan',startX:e.clientX,startY:e.clientY,x:view.x,y:view.y}}
function pointerMove(e,root,editor){if(!editor||!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&pinch){const p=[...pointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);view.scale=clamp(pinch.scale*d/pinch.distance,.35,2.5);view.x=pinch.x+(((p[0].x+p[1].x)/2)-pinch.midX);view.y=pinch.y+(((p[0].y+p[1].y)/2)-pinch.midY);render(root,editor);return}if(!drag)return;if(drag.kind==='pan'){view.x=drag.x+e.clientX-drag.startX;view.y=drag.y+e.clientY-drag.startY;render(root,editor)}else{const dx=(e.clientX-drag.startX)/view.scale,dy=(e.clientY-drag.startY)/view.scale;const el=root.querySelector(`[data-table="${drag.id}"]`);if(el){el.style.left=snap(drag.x+dx)+'px';el.style.top=snap(drag.y+dy)+'px'}}e.preventDefault()}
function pointerUp(e,root,editor){pointers.delete(e.pointerId);if(drag?.kind==='table'){const el=root.querySelector(`[data-table="${drag.id}"]`),x=parseFloat(el.style.left),y=parseFloat(el.style.top);update(s=>{const t=s.tables.find(x=>x.id===drag.id);t.x=x;t.y=y},{label:'Moved table'}).then(()=>render(root,editor))}drag=null;if(pointers.size<2)pinch=null}
function bindInspector(root){const box=root.querySelector('.floating-inspector');box.onclick=e=>{if(e.target.dataset.closeInspector!==undefined){selected=null;render(root,true)}if(e.target.dataset.seat)update(s=>{const t=s.tables.find(x=>x.id===selected);t.capacity=clamp(t.capacity+Number(e.target.dataset.seat),1,30)},{label:'Changed seats'}).then(()=>render(root,true));if(e.target.dataset.rotate)update(s=>{const t=s.tables.find(x=>x.id===selected);t.rotation=(t.rotation+Number(e.target.dataset.rotate)+360)%360},{label:'Rotated table'}).then(()=>render(root,true));if(e.target.dataset.duplicate!==undefined)update(s=>{const t=s.tables.find(x=>x.id===selected);const c={...t,id:uid(),number:String(Math.max(0,...s.tables.map(x=>parseInt(x.number)||0))+1),x:t.x+30,y:t.y+30,partyId:null,status:'available'};s.tables.push(c);selected=c.id},{label:'Duplicated table'}).then(()=>render(root,true));if(e.target.dataset.delete!==undefined&&confirm('Delete this table?'))update(s=>{s.tables=s.tables.filter(x=>x.id!==selected);selected=null},{label:'Deleted table'}).then(()=>render(root,true))};box.onchange=e=>update(s=>{const t=s.tables.find(x=>x.id===selected);if(e.target.dataset.shape!==undefined)t.shape=e.target.value;if(e.target.dataset.number!==undefined)t.number=e.target.value;if(e.target.dataset.section!==undefined)t.section=e.target.value;if(e.target.dataset.width!==undefined)t.width=clamp(Number(e.target.value)||120,50,500);if(e.target.dataset.height!==undefined)t.height=clamp(Number(e.target.value)||90,40,400)},{label:'Edited table'}).then(()=>render(root,true))}
function addTable(shape,root){update(s=>s.tables.push({id:uid(),number:String(Math.max(0,...s.tables.map(x=>parseInt(x.number)||0))+1),capacity:shape==='round'?2:shape==='bar'||shape==='banquet'?8:4,x:120,y:120,width:shape==='round'?100:shape==='bar'||shape==='banquet'?220:150,height:shape==='bar'?65:100,rotation:0,shape,section:'Main',status:'available'}),{label:'Added table'}).then(()=>render(root,true))}
function addObject(type,root){update(s=>{s.objects=s.objects||[];s.objects.push({id:uid(),type,label:type.replaceAll('-',' '),x:180,y:180,width:type==='wall'?260:120,height:type==='wall'?18:70,rotation:0})},{label:'Added floor object'}).then(()=>render(root,true))}